[book]
authors = ["move-cn"]
language = "cn"
multilingual = false
src = "src"
title = "Let's Move 101"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/move-cn/letsmove-101"

[output.html.playground]
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2